services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobdb
    networks:
      - jobnet
  app:
    image: node:22
    working_dir: /app
    volumes:
      - ./workspace/job-service-api:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    command: yarn start:dev
    tty: true
    networks:
        - jobnet
networks:
  jobnet:
