services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobdb
    networks:
      - jobnet
networks:
  jobnet:
